### ISSUE TITLE
Service Discovery based on tag (基于Tag过滤的服务发现能力)

### ISSUE THREAD

**Issue by hyu35** [kitex-contrib/registry-etcd#10]
**Is your feature request related to a problem? Please describe.**
当多个研发在同一个需求中开发多个服务时，为了避免弄脏基准环境，预期可以有能力部署多泳道开发环境。

**Describe the solution you'd like**
目前想到的是在基准环境中建立需求功能环境，并将被修改的工程使用“功能环境标”签作为Tag注册到ETCD。

在测试流量中注入”功能环境标签“，Client在做服务发现时候，可基于该标签对Tag进行过滤，找出该功能环境中的实例，进行访问。（若无该标签的实例，则访问基准环境）。

**Describe alternatives you've considered**
暂无

**Additional context**
暂无

**Comment by lizhemingi** [comment]
Yeah, I think it's a good proposal.

Do we have any best practice for this ? @GuangmingLuo

**Comment by GuangmingLuo** [comment]
Agree, we need to discuss this

**Comment by succulentxb** [comment]
Cannot agree anymore

**Comment by ppzqh** [comment]
@hyu35 @succulentxb I have added one issue for enhancement in cloudwego/kitex. You may check the update and share your ideas under that thread.

**Comment by ppzqh** [comment]
@hyu35 @succulentxb @lizhemingi Please check the new extension in kitex-contrib for this feature. https://github.com/kitex-contrib/resolver-rule-based
