### ISSUE TITLE
无法获取模块github.com/kitex-contrib/registry-etcd/retry

### ISSUE THREAD

**Issue by aaravarr** [kitex-contrib/registry-etcd#30]
copy了一下example的代码

go: module github.com/kitex-contrib/registry-etcd@upgrade found (v0.1.1), but does not contain package github.com/kitex-contrib/registry-etcd/retry

![image](https://github.com/kitex-contrib/registry-etcd/assets/92586826/0cbc5a9c-18df-4483-ad81-7ae5857e0568)

**Comment by Skyenought** [comment]
@chaoranz758 PTAL

**Comment by chaoranz758** [comment]
> copy了一下example的代码
> 
> go: module github.com/kitex-contrib/registry-etcd@upgrade found (v0.1.1), but does not contain package github.com/kitex-contrib/registry-etcd/retry
> 
> ![image](https://user-images.githubusercontent.com/92586826/271765278-0cbc5a9c-18df-4483-ad81-7ae5857e0568.png)

go get github.com/kitex-contrib/registry-etcd@e697f9fcefc35e55a92c6758ae75cfa574bf746e 
使用这个命令获取最新 commit 的代码

**Comment by Skyenought** [comment]
@ahaostudy

**Comment by aaravarr** [comment]
okk，好了好了
