### ISSUE TITLE
服务发现的案例缺少watch机制

### ISSUE THREAD

**Issue by someview** [kitex-contrib/registry-etcd#31]
kitex提供的服务发现接口，本身不包含watch, 那服务节点变更了，客户端怎么可能能动态知道呢，你们给出的这些例子简直把我看麻了.
在客户端服务发现的代码里面添加watch，这个我觉得应该是必须要有的吧

**Comment by li-jin-gou** [comment]
same to https://github.com/cloudwego/kitex/discussions/330
