### ISSUE TITLE
mac goland 老是提示加载错误

### ISSUE THREAD

**Issue by zhaoliubox** [kitex-contrib/registry-etcd#35]
这个库的gomod为什么要引入kitex-examplesni2

go: loading module retractions for github.com/cloudwego/kitex-examples@v0.2.4: verifying go.mod: github.com/cloudwego/kitex-examples@v0.3.2/go.mod: reading https://goproxy.cn/sumdb/sum.golang.org/lookup/github.com/cloudwego/kitex-examples@v0.3.2: 404 Not

**Comment by aaravarr** [comment]
这个问题是 kitex-examples v0.3.2 版本丢失造成的，刚刚发布了 v0.3.3 ，你可以先将本地依赖更新到 0.3.3 来解决这个问题。至于该库对 kitex-exmaples 的依赖问题我们会在后续处理
