### ISSUE TITLE
提供的 etcd 服务注册的默认 key 是 kitex/registry-etcd/%v/  ，这里有没有自定义 key 的配置吗？

### ISSUE THREAD

**Issue by dongpoge** [kitex-contrib/registry-etcd#36]
在 common.go 里，看到了 获取 key 的方法：
`
const (
	etcdPrefixTpl = "kitex/registry-etcd/%v/"
)

func serviceKeyPrefix(serviceName string) string {
	return fmt.Sprintf(etcdPrefixTpl, serviceName)
}

// serviceKey generates the key used to stored in etcd.
func serviceKey(serviceName, addr string) string {
	return serviceKeyPrefix(serviceName) + addr
}
`

但是我如果想修改 默认的 key ，好像没有找到配置的地方

**Comment by aaravarr** [comment]
参考一下[文档](https://www.cloudwego.io/zh/docs/kitex/tutorials/service-governance/service_discovery/etcd/#%E5%AE%9E%E4%BE%8B%E4%BF%A1%E6%81%AF)，目前不支持自定义整个 Key，可以在解析时使用 `kitex/registry-etcd/{serviceName}` 前缀进行查找，你有什么特殊的需求吗

**Comment by li-jin-gou** [comment]
已支持 @leader318 ，我们打个 tag 补充一下文档

**Comment by dongpoge** [comment]
感谢，很效率👍
