### ISSUE TITLE
待修复

### ISSUE THREAD

**Issue by pp292** [kitex-contrib/registry-etcd#41]
版本
go 1.22.2

github.com/kitex-contrib/registry-etcd v0.2.4

服务注册 etcd.NewEtcdRegistryWithRetry 链接etcd一定要设置 etcd.WithEtcdServicePrefix("")，否则默认的Prefix: "kitex/registry-etcd"形同虚设。

默认不设置 etcd.WithEtcdServicePrefix 情况下，服务注册并没有设置 kitex/registry-etcd 前缀，而client去请求找etcd服务的时候，又会根据 kitex/registry-etcd 前缀去找。

导致一直出错，提示 service discovery error: no instance remains for XXXX

**Comment by DMwangnima** [comment]
方便看一下你在 server 侧的代码么？

**Comment by pp292** [comment]
retryConfig := retry.NewRetryConfig(
		retry.WithMaxAttemptTimes(config.MaxAttemptTimes)),
		retry.WithObserveDelay(config.ObserveDelay*time.Second),
		retry.WithRetryDelay(config.RetryDelay*time.Second),
	)
	r, err = etcd.NewEtcdRegistryWithRetry(config.Hosts, retryConfig)

这个代码会出现错误，但是设置前缀后正常了。

	retryConfig := retry.NewRetryConfig(
		retry.WithMaxAttemptTimes(config.MaxAttemptTimes)),
		retry.WithObserveDelay(config.ObserveDelay*time.Second),
		retry.WithRetryDelay(config.RetryDelay*time.Second),
	)
	r, err = etcd.NewEtcdRegistryWithRetry(config.Hosts, retryConfig, etcd.WithEtcdServicePrefix(""))

使用  /usr/local/etcd/etcdctl get "" --prefix --keys-only 看过注册的服务，确实是新注册的服务没有kitex/registry-etcd前缀

**Comment by GuangmingLuo** [comment]
@pp292 请遵守社区守则，友善反馈问题，我们不欠你啥，“巨坑”是啥意思？开源项目使用过程中遇到问题提出问题解决问题即可。

**Comment by DMwangnima** [comment]
@pp292 这里确实遗漏了注入 prefix 到 etcdRegistry 中
![image](https://github.com/user-attachments/assets/d7d6ac96-4c68-41a0-a5c2-d8aa003f2551)
有兴趣提个 PR 修复下么？
另外可以修改一下 issue 标题么，我们的 kitex-contrib 项目是社区同学在百忙中抽出时间贡献得到的，“巨坑”确实有些言重了。

**Comment by pp292** [comment]
> @pp292 这里确实遗漏了注入 prefix 到 etcdRegistry 中 ![image](https://private-user-images.githubusercontent.com/33331974/364599578-d7d6ac96-4c68-41a0-a5c2-d8aa003f2551.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MDc4NTgsIm5iZiI6MTcyNTUwNzU1OCwicGF0aCI6Ii8zMzMzMTk3NC8zNjQ1OTk1NzgtZDdkNmFjOTYtNGM2OC00MWEwLWE1YzItZDhhYTAwM2YyNTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDAzMzkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNTE2ODgzODI3ODRkYjkyYjJiZjliNjNhMWY2ODk1MDY3YTkyMGIzMzAwMjFjM2QyZmYyMmQ5OGZhMmM0ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RhceK3nhd0AoakQWk4LVWegcIfN8683g7cdQ6pLF2w4) 有兴趣提个 PR 修复下么？ 另外可以修改一下 issue 标题么，我们的 kitex-contrib 项目是社区同学在百忙中抽出时间贡献得到的，“巨坑”确实有些言重了。

你的回复比较客观，不像有些同学。

**Comment by DMwangnima** [comment]
@pp292 v0.2.5 已修复这个问题，请试用一下。如果 ok 的话，这个 issue 可以 close 了。

**Comment by li-jin-gou** [comment]
这个 PR 引入的 bug https://github.com/kitex-contrib/registry-etcd/pull/34 cc @logicwu0
