### ISSUE TITLE
可以支持etcd的tls证书认证吗

### ISSUE THREAD

**Issue by zmdaily404** [kitex-contrib/registry-etcd#8]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lizhemingi** [comment]
Yep, I totally agree to add this feature. 
would you like to implement it? pr is welcome.

**Comment by GuangmingLuo** [comment]
Your PR has been merged, can you join our feishu chat group and reach out to me ?  @zmdaily404 
> find the QR code in the readme: https://github.com/cloudwego/kitex
